SUPABASE_URL = "https://aveyncgmhfeoysfrarlg.supabase.co"
SUPABASE_KEY = "sb_publishable_1YumvUbaiK2YomrkDebwIw_50ye4RtT"
ADMIN_ID = "admin"
ADMIN_PASSWORD = "0000"

DEV_ID = "developer"
DEV_PASSWORD = "0000"